.\" Copyright (C) 2016-current Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSAutoregression 3 2025-01-20 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSAutoregression\fR \- Forward inputs to model (autoregression)

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/psyc.h>

.I
int  
.br
\fBPSAutoregression\fR(\fIPSModel *model\fR, \fIPSFloat *inputs\fR, \fIint randomized\fR, \fIPSSequenceSettings *sequence_settings\fR)
.SH DESCRIPTION
Forward \fIinputs\fR to \fImodel\fR with autoregression mode. The model must take sequences as inputs and produce sequences as outputs.
.br
If \fImodel\fR is part of a multi-model chain, \fIinputs\fR are forwarded to the first layer of the first model of the chain and outputs are produced by the last layer of the last model of the chain.
.br
When the full input sequence as been forwarded, all subsequent outputs produced by the model (including the last outputs produced by the input sequence) are forwarded as the next inputs to the model itself.
.br
The size of the output layer must match the size of the input layer or, if the input layer has the \fIPS_FLAG_ONEHOT\fR set, its \fIonehot_vector_size\fR.
.br
If the input layer has the \fIPS_FLAG_ONEHOT\fR set, the index of the highest element of the produced outputs is forwarded to the input layer. In this case, if the \fIrandomized\fR argument is true, a random index is generated by using the values of the outputs as a probability distribution.
.br
The iteration keeps forwarding outputs as the next inputs until one of the following events happens:
.br

.RS 4
\[bu] The length of the whole output sequence produced (including the outputs produced by the original input sequence) reaches the maximum length defined into the (optional) argument \fIsequence_settings\fR or by the default value of \fIPS_MAX_SEQUENCE_LENGTH\fR.
.br

\[bu] The index of the highest value of the produced outputs matches the value of \fIend\fR in the optional argument \fIsequence_settings\fR. If the \fIrandomized\fR argument is true, the random index generated by using outputs as a probability distribution is compared with \fIend\fR. If \fIsequence_settings\fR is \fINULL\fR or the value of the \fIend\fR member is negative, the end-matching event is ignored.
.RE
.RE


.SH RETURN VALUES
1 if the process succeeds or 0 if:

.RS 4
\[bu] \fImodel\fR is \fINULL\fR
.br

\[bu] \fImodel\fR is not built.
.br

\[bu] The input layer doesn't take sequences as inputs and the output layer doesn't produce sequences as outputs.
.br

\[bu] The size of the output layer doesn't match the size of the input layer (or input layer's \fIonehot_vector_size\fR if the input layer has the flag \fIPS_FLAG_ONEHOT\fR set).
.br

\[bu] Something else in the forward process fails.
.br
.RE

.SH SEE ALSO
psyc(1), PSClassify(3), PSClassifyImage(3), PSForward(3)
