.\" Copyright (C) 2016-current Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSBLASErrorStr 3 2025-01-20 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSBLASErrorStr\fR

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/blas.h>

.I
const char  *
.br
\fBPSBLASErrorStr\fR(\fIPSBLASErr *err\fR, \fIconst char ** param_names\fR)
.SH DESCRIPTION
Get a string representing the BLAS error \fIerr\fR. If `err->param` is \fINULL\fR, the optional \fIparam_names\fR argument can be used to pass the names of the parameters (determined by 1-based err->param_pos value).
.br

.br
\fBNOTE\fR:  the returned string is a \fIstatic\fR string: it should never be freed and it's always overwritten by subsequent calls.
.br

.SH RETURN VALUES
The error string of \fINULL\fR if \fIerr\fR is \fINULL\fR.

.SH SEE ALSO
psyc(1)
