.\" Copyright (C) 2016-current Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSDictSet 3 2025-01-20 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSDictSet\fR \- Set item for key

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/utils.h>

.I
PSDictItem  *
.br
\fBPSDictSet\fR(\fIPSDict *dict\fR, \fIconst char *key\fR, \fIPSDictValue val\fR)
.SH DESCRIPTION
Set value \fIval\fR for key \fIkey\fR in dictionary \fIdict\fR. Unless flag \fIPSDICT_UPDATE_DISABLED\fR is enabled in dictionary flags, value will be set even If \fIkey\fR is already associated to another value.  

.SH RETURN VALUES
The item (\fIPSDictItem\fR) associated to the \fIkey\fR or \fINULL\fR.

.SH SEE ALSO
psyc(1)
