.\" Copyright (C) 2016-2024 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSDot 3 2024-03-09 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSDot\fR \- matrix\-matrix multiplication

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
int  
.br
\fBPSDot\fR(\fIPSMatrix a\fR, \fIPSMatrix b\fR, \fIPSFloat *dest\fR, \fIPSMathOpts *opts\fR)
.SH DESCRIPTION
Performs matrix-matrix multiplication, matrix-vector multiplication, vector-matrix multiplication or vector-vector multiplication, depending on the value of \fIargtype\fR field in opts (default is matrix-matrix).
.br
The resulting vector is stored into \fIdest\fR.
.br
The function can take advantage of the available accelerations (both hardwware and software). By default, accelerations set in \fIPSGlobalAcceleration\fR are used, if any. However, the used accelerations methods can be changed via the \fIacceleration\fR member of the optional argument \fIopts\fR.
.br
Aside from acceleration, \fIopts\fR can also be used to set the result storage mode (by using the \fIstore_mode\fR member):
.br

.RS 4
.TP
.B PS_STORE_MODE_ADD
the result is added to the existing values of \fIdest\fR.
.br

.TP
.B PS_STORE_MODE_SUB
the result is subtracted from the existing values    of \fIdest\fR.
.RE
.RE

.br
\fBNOTE\fR:  if \fIargtype\fR for both \fIa\fR and \fIb\fR is 'V', the function will compute the dot product of the two vectors, assuming that they have the same size.
.br
If you need to perform matrix multiplication on two PSFloat arrays, use \fIPSMatMul\fR instead.  

.SH RETURN VALUES
1 in case of success, 0 in case of failure.
Possible failure reasons:
.br

.RS 4
\[bu] \fIa\fR is \fINULL\fR or \fIb\fR is \fINULL\fR or \fIdest\fR is \fINULL\fR.
.br

\[bu] Memory allocation failure.
.br

\[bu] \fIa\fR is vector or \fIb\fR is vector and the resulting length would be zero.
.br

\[bu] Both \fIa\fR and \fIb\fR are vectors but \fIvector_len\fR member of optional \fIopts\fR argument is zero or \fIopts\fR is \fINULL\fR.
.br
.RE

.SH SEE ALSO
psyc(1), PSMatMul(3)
