.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSDot 3 2023-12-01 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
PSDot

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
int  
.br
\fBPSDot\fR(\fIPSMatrix a\fR, \fIPSMatrix b\fR, \fIPSFloat *dest\fR, \fIPSMathOpts *opts\fR)
.SH DESCRIPTION
Performs matrix-matrix multiplication, matrix-vector multiplication, vector-matrix multiplication or vector-vector multiplication, depending on the value of \fIargtype\fR field in opts (default is matrix-matrix).
.br
Store result is \fIdest\fR.  

.SH RETURN VALUES
1 in case of success, 0 in case of failure.

.br
\fBNOTE\fR:  if \fIargtype\fR for both \fIa\fR and \fIb\fR is 'V', the function will compute the dot product of the two vectors, assuming that they have the same size.
.br
If you need to perform matrix multiplication on two PSFloat arrays, use \fIPSMatMul\fR instead.
