.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSGaussianRandom 3 2023-12-09 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
\fBPSGaussianRandom\fR \- Get random number from a gaussian distribution

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
PSFloat  
.br
\fBPSGaussianRandom\fR(\fIPSFloat mean\fR, \fIPSFloat stddev\fR)
.SH DESCRIPTION
Generate a random floating number from a gaussian distribution having mean defined by \fImean\fR and standard deviation defined by \fIstddev\fR.  

.SH RETURN VALUES
The random float number.

.SH SEE ALSO
psyc(1)
