.\" Copyright (C) 2016-current Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSGelu 3 2025-01-20 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSGelu\fR \- GELU activation function

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/activation.h>

.I
void  
.br
\fBPSGelu\fR(\fIPSFloat *vec\fR, \fIPSFloat *dest\fR, \fIlong len\fR, \fIint acceleration\fR)
.SH DESCRIPTION
GELU (Gaussian Error Linear Units) activation function for vectors.
.br
GELU is computed on vector \fIvec\fR of length \fIlen\fR and stored into vector \fIdest\fR.
.br
If \fIdest\fR is \fINULL\fR, results will be stored into \fIvec\fR itself.
.br
For the \fIacceleration\fR argument, take a look at \fIPSAcceleration\fR.
.br
For info about GeLU:
.br
  \fIhttps://arxiv.org/abs/1606.08415\fR
.br
The equivalent function to be used with scalars is \fIPSGeLUS\fR.
.br
The derivative of this function is \fIPSGeLUDerivative\fR.

.SH SEE ALSO
psyc(1)
