.\" Copyright (C) 2016-2024 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSLayerSave 3 2024-01-03 "PsyC 0.9.4" "PsyC Library Functions Manual"

.SH NAME
\fBPSLayerSave\fR \- Save layer to file

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/psyc.h>

.I
int  
.br
\fBPSLayerSave\fR(\fIPSLayer *layer\fR, \fIconst char *filepath\fR, \fIint opts\fR)
.SH DESCRIPTION
Save \fIlayer\fR to file located at \fIfilepath\fR. By default, only the layer's trainable parameters (ie. weights, biases) are saved and the layer is saved in ASCII format.
.br
However, this behavior can be changed by setting the following flags into the \fIopts\fR argument:
.br

.RS 4
.TP
.B PS_IO_BINARY_MODE
save the layer data in binary format.
.br

.TP
.B PS_IO_SAVE_DEFINITION
also save layer's properties (ie. type, size, ...). This option cannot be used along with \fIPS_IO_BINARY_MODE\fR.
.RE
.RE


.SH RETURN VALUES
1 if the layer is saved, 0 if somethign goes wrong.
Possible failure reasons:
.br

.RS 4
\[bu] The \fIlayer\fR argument is \fINULL\fR.
.br

\[bu] Both \fIPS_IO_BINARY_MODE\fR and \fIPS_IO_SAVE_DEFINITION\fR are set.
.br

\[bu] The file at \fIfilepath\fR cannot be opened for writing.
.br

\[bu] Some error occurs qhile writing data.
.br
.RE

.SH SEE ALSO
psyc(1)
