.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSLoadDataFromTextFile 3 2023-12-01 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
PSLoadDataFromTextFile

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/dataset.h>

.I
PSFloat  *
.br
\fBPSLoadDataFromTextFile\fR(\fIconst char *filepath\fR, \fIPSTextParserOptions *opts\fR, \fIint64_t *datalen\fR, \fIPSVocabulary ** vocabulary\fR)
.SH DESCRIPTION
Load a dataset (an array of PSFloat numbers) from the text file found at \fIfilepath\fR.
.br
For parsing options and other arguments, see \fIPSLoadDataFromString\fR.  

.SH RETURN VALUES
The dataset (\fIPSFloat\fR array) or \fINULL\fR is something goes wrong.

.SH SEE ALSO
PSLoadDataFromString(3)
