.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSLoadDataFromString 3 2023-12-01 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
PSLoadDataFromString

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/dataset.h>

.I
PSFloat  *
.br
\fBPSLoadDataFromString\fR(\fIchar *str\fR, \fIPSTextParserOptions *opts\fR, \fIPSFloat *existing_data\fR, \fIint64_t *datalen\fR, \fIPSVocabulary ** vocabulary\fR)
.SH DESCRIPTION
Load a dataset (an array of \fIPSFloat\fR numbers) from a string. Depending on the parsing mode, each token or character found in the string will be converted to a numeric representation of itself. The dataset can be used to train a model (\fIPSModel\fR) or it can provide inputs to the model.
.br
Numeric representation of tokens/characters is defined by key-value pairs contained into \fIvocabulary\fR and indices (ids) related to token are cast to \fIPSFloat\fR.
.br
The function can use an existing vocabulary or create a new one from scratch.
.br
By default, the string will be parsed as a sequence of tokens (\fIPS_PARSER_MODE_TOKENS\fR) and each token will be converted to a number.
.br
The above behavior can be changed by using \fIPS_PARSER_MODE_CHARS\fR in the (optional) \fIopts\fR argument (see \fIPSTextParserOptions\fR).
.br

.br
When \fIPS_PARSER_MODE_TOKENS\fR mode is used, tokens can be matched in two ways:
.br

.RS 4
\[bu] By using a separator: in this case the string will be split by using the separators defined into \fIseparator\fR member of \fIopts\fR. If \fIseparator\fR is \fINULL\fR or \fIopts\fR is \fINULL\fR, the default separators will be those defined by the macro \fIPS_DEFAULT_TOKEN_SEPARATOR\fR.
.br

\[bu] By using a callback that let the developers to define their own logic for identifying and extracting tokens from the input string. The callback function can be set into the \fImatch_token\fR member of \fIopts\fR, and it's a function of type \fIPSTokenMatch\fR. The callback receives a token to match and a pointer to an integer to store the length of the matched token. If the callback returns a non-zero value (true), it indicates a successful match and a token of the matched length will be extracted from the input string. In this case, the parsing position is moved forward by the matched length. If the callback returns 0, it signals that the token was not matched, and the parsing position will be advanced to the next byte.
.RE
.RE

.br
\fBWARN\fR:  The parsed string \fIstr\fR may be modified during text parsing. By setting the \fIPS_PARSER_FLAG_PRESERVE_STRING\fR flag into `opts->flags`, the function will work on a copy of the string, preventing the original string from being altered.
.br

.br
.B ARGUMENTS
.br

.RS 4
.TP
.B str
the (null-terminated) string to be parsed (mandatory).
.br

.TP
.B opts
parsing options, it can be \fINULL\fR.
.br

.TP
.B existing_data
optional argument that can be used to append    parsed data to an existing dataset. WARN: Since data can be reallocated, always use the returned dataset after calling the function.
.br

.TP
.B datalen
pointer to \fIuint64_t\fR where the final length of the dataset    will be stored. If \fIexisting_data\fR is not \fINULL\fR, the address pointed by \fIdatalen\fR must contain the current length of the existing dataset. If \fINULL\fR is returned by the function, the pointed address will contain zero.
.br

.TP
.B vocabulary
pointer to pointer to a \fIPSVocabulary\fR struct. The    argument is mandatory and cannot be \fINULL\fR. If the pointer pointed by \fIvocabulary\fR is \fINULL\fR, a new \fIPSVocabulary\fR will be allocated and it will be filled with parsed tokens|characters. If the pointer pointed by \fIvocabulary\fR points to an already existing vocabulary, its numeric values will be used for parsed tokens. If a token or character is not found in the existing vocabulary, it will be automatically added, unless \fIPS_PARSER_FLAG_READONLY_VOCAB\fR flag is set into \fIopts\fR.
.RE
.RE


.SH RETURN VALUES
The dataset (\fIPSFloat\fR array) or \fINULL\fR is something goes wrong.
