.\" Copyright (C) 2016-current Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSMatrixEquals 3 2025-01-20 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSMatrixEquals\fR \- Compare two martrices

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
int  
.br
\fBPSMatrixEquals\fR(\fIPSMatrix a\fR, \fIPSMatrix b\fR, \fIint precision\fR, \fIint ignore_shape\fR)
.SH DESCRIPTION
Compare two martrices \fIa\fR and \fIb\fR having \fIlength\fR length. Use \fIprecision\fR to set precision tolerance. Lower precision leads to higher tolerance.
.br
By setting \fIprecision\fR to zero, the two vectors must be perfectly equal (no precision tolerance at all).  

.SH RETURN VALUES
1 if \fIa\fR and \fIb\fR equal, 0 if they differ at some point.

.SH SEE ALSO
psyc(1)
