.\" Copyright (C) 2016-2024 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSMatrixSqueeze 3 2024-04-06 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSMatrixSqueeze\fR

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
PSMatrix  
.br
\fBPSMatrixSqueeze\fR(\fIPSMatrix matrix\fR)
.SH DESCRIPTION
Create a new matrix having the same values of \fImatrix\fR and after removing all unnecessary axes of length one from the original shape of \fImatrix\fR.
.br
For example, a matrix having shape of (1, 2, 3) will generate a matrix with shape (2, 3).  

.SH RETURN VALUES
The "squeezed" matrix or \fINULL\fR if:

.RS 4
\[bu] \fImatrix\fR is \fINULL\fR or empty.
.br

\[bu] The new matrix cannot be created/allocated.
.br
.RE

.SH SEE ALSO
psyc(1)
