.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSMatrixWithGaussianRandom 3 2023-12-09 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
\fBPSMatrixWithGaussianRandom\fR

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
PSMatrix  
.br
\fBPSMatrixWithGaussianRandom\fR(\fIPSFloat stddev\fR, \fIint ndims\fR, \fI...\fR)
.SH DESCRIPTION
Create a new matrix having number of dimensions defined by \fIndims\fR. The shape of the matrix is given by variadic arguments that follow \fIndims\fR.
.br
The values of the matrix will be initialized with random numbers from a gaussian distribution having zero mean and the standard deviation defined by \fIstddev\fR.
.br
If the matrix cannot be allocated, \fIerrno\fR will be set to \fIENOMEM\fR.  

.SH RETURN VALUES
The allocated matrix or \fINULL\fR if:

.RS 4
\[bu] the number of dimensions (\fIndims\fR) is greater than \fIPS_MATRIX_MAX_DIMENSIONS\fR or less than one.
.br

\[bu] it's not possible to allocate the matrix in memory.
.RE
.RE

.br
\fBWARN\fR:  the address pointed by the returned pointer should never be freed directly. The specific function \fIPSMatrixFree\fR should be used instead.
.br

.SH SEE ALSO
psyc(1)
