.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSMatrixExpand 3 2023-12-01 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
PSMatrixExpand

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
PSMatrix  
.br
\fBPSMatrixExpand\fR(\fIPSMatrix src\fR, \fIint add\fR, \fIint keep_src\fR)
.SH DESCRIPTION
Expand matrix \fIsrc\fR by adding \fIadd\fR to its first dimension. Added data will be set to zero.
.br
Beware of the fact that \fIsrc\fR matrix could be freed after the process, so always assing the return value of this function to a new variable, since it could lead to memory leaks in case of a \fINULL\fR return value. Also beware of the fact that the original variable holding \fIsrc\fR could point to freed memry after function returns.
