.\" Copyright (C) 2016-2024 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSMatrixIsTransposedVersion 3 2024-04-06 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSMatrixIsTransposedVersion\fR

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
int  
.br
\fBPSMatrixIsTransposedVersion\fR(\fIPSMatrix matrix\fR)
.SH DESCRIPTION
Check whether \fImatrix\fR is the cached trasposed version of another matrix created by \fIPSMatrixTranspose\fR.  

.SH RETURN VALUES
1 if \fImatrix\fR is not \fINULL\fR and is a cached transposed version, 0 otherwise.

.SH SEE ALSO
psyc(1), PSMatrixTranspose(3)
