.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSMatrixProduct 3 2023-12-07 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
PSMatrixProduct

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
int  
.br
\fBPSMatrixProduct\fR(\fIPSMatrix a\fR, \fIPSMatrix b\fR, \fIPSMatrix *result\fR, \fIPSMathOpts *opt\fR)
.SH DESCRIPTION
Performs matrix-matrix multiplication between matrix \fIa\fR and matrix \fIb\fR.
.br
Results are stored into matrix pointed by \fIresult\fR. If pointer pointed by \fIresult\fR is \fINULL\fR, a new matrix is automatically allocated by the function itself and its pointer will be stored into \fIresult\fR.
.br
The \fIopt\fR argument can be \fINULL\fR.
.br
By default, function uses BLAS to compute the result. Anyway, if BLAS support is missing in PsyC build and \fIb\fR only has one dimension, function will try compute results by using \fIPSDotProduct\fR.
.br
The acceleration method can be changed via the \fIacceleration\fR member of the optional \fIopt\fR argument.
.br
Matrices can be transpose by using the \fItranspose\fR field in the \fIopt\fR argument. In that case, \fItranspose\fR will contain the (1-based) indices of the matrix arguments you want to be transposed:
.br

.RS 4
\[bu] opt->transpose = 1 (transpose matrix \fIa\fR)
.br

\[bu] opt->transpose = 2 (transpose matrix \fIb\fR)
.br

\[bu] opt->transpose = (1 | 2) (transpose both matrix \fIa\fR and \fIb\fR)
.RE
.RE

By default, data in result vector will be overwritten. Anyway, if \fIPS_STORE_MODE_ADD\fR is set as \fIstore_mode\fR into \fIopt\fR, result will be added to data already present in the result vector.  

.SH RETURN VALUES
1 if operation succeeds, 0 if it fails.
Possible failure reasons:
.br

.RS 4
\[bu] \fIresult\fR is \fINULL\fR or \fIa\fR is \fINULL\fR or \fIb\fR is \fINULL\fR.
.br

\[bu] \fIa\fR has zero dimensions or \fIb\fR has zero dimensions.
.br

\[bu] Matrix aligment error.
.br

\[bu] Invalid result shape.
.br

\[bu] Matrix pointed by \fIresult\fR is not \fINULL\fR and its shape differs from resulting output shape.
.br

\[bu] Memory allocation failure.
.br
.RE

.SH SEE ALSO
PSDotProduct(3), PSMatrixProductMV(3), PSMatrixProductVM(3)
