.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSModelRebuild 3 2023-12-01 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
PSModelRebuild

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/psyc.h>

.I
int  
.br
\fBPSModelRebuild\fR(\fIPSModel *model\fR)
.SH DESCRIPTION
Rebuild an already built \fImodel\fR by resetting its \fIbuilt\fR state and calling \fIPSModelBuild\fR. If \fImodel\fR is not built, calling this function is the same as directly calling \fIPSModelBuild\fR.  

.SH RETURN VALUES
See \fIPSModelBuild\fR.

.SH SEE ALSO
PSModelBuild(3), PSModelIsBuilt(3)
