.\" Copyright (C) 2016-2023 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSReluDerivative 3 2023-12-01 "PsyC 0.9.3" "PsyC Library Functions Manual"

.SH NAME
PSReluDerivative

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/activation.h>

.I
void  
.br
\fBPSReluDerivative\fR(\fIPSFloat *vec\fR, \fIPSFloat *dest\fR, \fIuint64_t len\fR, \fIPSMathOpts *opts\fR)
.SH DESCRIPTION
Computes the derivative of ReLU activation function (\fIPSRelu\fR) for vectors.
.br
The derivative is computed on vector \fIvec\fR of length \fIlen\fR and stored into vector \fIdest\fR.
.br
If \fIdest\fR is \fINULL\fR, results will be stored into \fIvec\fR itself.
.br
The \fIopts\fR argument can be used to change default acceleration used to compute results (see \fIPSMathOpts\fR).
.br
The equivalent function to be used with scalars is \fIPSReluDerivativeS\fR.

.SH SEE ALSO
PSRelu(3), PSReluDerivativeS(3)
