.\" Copyright (C) 2016-2024 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSRelu 3 2024-03-09 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSRelu\fR \- ReLU activation function

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/activation.h>

.I
void  
.br
\fBPSRelu\fR(\fIPSFloat *vec\fR, \fIPSFloat *dest\fR, \fIlong len\fR, \fIint acceleration\fR)
.SH DESCRIPTION
ReLU (Rectified Linear Unit) activation function for vectors.
.br
ReLU is computed on vector \fIvec\fR of length \fIlen\fR and stored into vector \fIdest\fR.
.br
If \fIdest\fR is \fINULL\fR, results will be stored into \fIvec\fR itself.
.br
For the \fIacceleration\fR argument, take a look at \fIPSAcceleration\fR.
.br
For info about ReLU:
.br
  \fIhttps://en.wikipedia.org/wiki/Rectifier_(neural_networks\fR)
.br

.br
The equivalent function to be used with scalars is \fIPSReluS\fR.
.br
The derivative of this function is \fIPSReluDerivative\fR.

.SH SEE ALSO
psyc(1), PSReluDerivative(3), PSReluS(3)
