.\" Copyright (C) 2016-2024 Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSVectorTranspose 3 2024-01-03 "PsyC 0.9.4" "PsyC Library Functions Manual"

.SH NAME
\fBPSVectorTranspose\fR \- Transpose vector

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/maths.h>

.I
PSFloat  *
.br
\fBPSVectorTranspose\fR(\fIPSFloat *vec\fR, \fIPSFloat *dest\fR, \fIint acceleration\fR, \fIint ndims\fR, \fI...\fR)
.SH DESCRIPTION
Create a transposed version of \fIvec\fR, considering it a matrix with a shape of \fIndims\fR dimensions.
.br
Variadic arguments can be used to define the shape of the matrix (that must have max. \fIPS_MATRIX_MAX_DIMENSIONS\fR dimensions).
.br
If \fIdest\fR is not \fINULL\fR, the transposed vector will be stored into memory pointed by \fIdest\fR itself.
.br
If \fIdest\fR is \fINULL\fR, the resulting vector will be allocated by the function.
.br
The function can take advantage of the available accelerations (both hardwware and software). By default, accelerations set in \fIPSGlobalAcceleration\fR are used, if any. However, the used accelerations methods can be changed via the \fIacceleration\fR member of the optional argument \fIopts\fR.
.br

.br
\fBNOTE\fR: 
.br

.RS 4
\[bu] The shape defined by the variadic dimensions refer to original shape of the vector (seen as a matrix) and not to the resulting transposed vector. So, if the defined shape is 2,3, the resulting shape will be 3,2.
.br

\[bu] If you need to transpose a \fIPSMatrix\fR, directly use \fIPSMatrixTranspose\fR instead.
.RE
.RE
.br

.SH RETURN VALUES
A pointer to the transposed vector, whose size will be the product of all dimensions of the defined shape or \fINULL\fR if something goes wrong.
If \fIdest\fR is not \fINULL\fR, return value will be \fIdest\fR or \fINULL\fR if something goes wrong.
.br
If \fIndims\fR is 1, the function will immediately return \fIvec\fR itself.
.br
Possible failure reasons:
.br

.RS 4
\[bu] \fIndims\fR is greater that \fIPS_MATRIX_MAX_DIMENSIONS\fR.
.br

\[bu] \fIndims\fR is zero or less than zero.
.br

\[bu] One of the shape's dimension in the variadic arguments is zero or less than zero.
.br

\[bu] Memory allocation failure.
.br
.RE

.SH SEE ALSO
psyc(1), PSMatrixTranspose(3)
