.\" Copyright (C) 2016-current Giuseppe Fabio Nicotra <artix2 at gmail dot com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms are permitted
.\" provided that the above copyright notice and this paragraph are
.\" duplicated in all such forms and that any documentation,
.\" advertising materials, and other materials related to such
.\" distribution and use acknowledge that the software was developed
.\" by the copyright holder. The name of the
.\" copyright holder may not be used to endorse or promote products derived
.\" from this software without specific prior written permission.
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

.TH PSVocabularySave 3 2025-01-20 "PsyC 0.9.5" "PsyC Library Functions Manual"

.SH NAME
\fBPSVocabularySave\fR \- Save vocabulary to file

.SH LIBRARY
PsyC (-lpsyc)

.SH SYNOPSIS

.B
#include <psyc/dataset.h>

.I
int  
.br
\fBPSVocabularySave\fR(\fIPSVocabulary *vocabulary\fR, \fIconst char *path\fR)
.SH DESCRIPTION
Save \fIvocabulary\fR to file located at \fIpath\fR. Vocabulary tokens are written sequentially to the file as an ordered sequence of \fINULL\fR-terminated strings.  

.SH RETURN VALUES
1 if the vocabulary has been successfully saved, 0 if:

.RS 4
\[bu] \fIvocabulary\fR is \fINULL\fR or \fIpath\fR is \fINULL\fR.
.br

\[bu] \fIpath\fR cannot be opened for writing.
.br

\[bu] Size of some token exceeds max. size (\fIPS_IO_MAX_TOKEN_SIZE\fR).
.br

\[bu] Some writing error occurs.
.br
.RE

.SH SEE ALSO
psyc(1)
